### ISSUE TITLE
docker-compose up is slow and redundant

### ISSUE THREAD

**Issue by klavins** [klavinslab/aquarium#340]
It would be nice if docker-compose up shouldn't have to do bundle install. And if it does have to do it, it would be nice if it didn't do it twice, once for rails and once for the Krill server.

**Comment by bjkeller** [comment]
Fixed in https://github.com/klavinslab/aquarium/commit/2a1c29200a4866e8efdd767bac52f7e6cd3832d9

It turns out that the bundler documentation [Dockerfiles for multiple Ruby applications and gems](https://bundler.io/v2.0/guides/bundler_docker_guide.html)  is sufficient despite the completely misleading section title.

It also turned out that there was a bug in the Dockerfile.
